### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: not opened

### ISSUE THREAD

**Issue by anba8005** [an-sh/ws-messaging#3]
Добрый день,

Огромное спасибо за прекрасную бибилиотеку, с удовольствием используем ее в одном из наших проектов. Приложение стандартное, броузерные клиенты и node.js серверная часть. Все делали по мануалу, однако иногда в консоли node.js вылетает следующая ошибка:

`(node:7572) UnhandledPromiseRejectionWarning: Error: not opened
    at WebSocket.send (/home/dev/videochat/videochat-node/node_modules/ws/lib/WebSocket.js:359:18)
    at cb (/home/dev/videochat/videochat-node/node_modules/ws-messaging/src/Client.js:492:49)
    at Promise (/home/dev/videochat/videochat-node/node_modules/ws-messaging/src/utils.js:23:5)
    at new Promise (<anonymous>)
    at fromCallback (/home/dev/videochat/videochat-node/node_modules/ws-messaging/src/utils.js:22:10)
    at attempt.then.then.data (/home/dev/videochat/videochat-node/node_modules/ws-messaging/src/Client.js:492:18)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
(node:7572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:7572) UnhandledPromiseRejectionWarning: Error: not opened`

В connectionHook помимо прочего используется валидация по Firebase token, поэтому исполнение промиса происходит через 250-300мс. Возможно это как-то связано ;)

Библиотека используется в связке с koa 2.5.0, node.js  8.11.2, Ubuntu linux 16.04 . Буду рад предоставить дополнительную информацию

**Comment by an-sh** [comment]
Да возможно где-то в есть рейс кондишн, между реальным вызовом send и проверкой на то что сокет отрыт. Можно попробовать заменить `client.send('connect', authReplyData) ` на `client.send('connect', authReplyData, () => {}) ` в https://github.com/an-sh/ws-messaging/blob/master/src/Server.js#L132.
